### ISSUE TITLE
nabd crashs in loop

### ISSUE THREAD

**Issue by cyril1929** [nabaztag2018/pynab#108]
After update on the last commit on master and reboot, nabd crashs in loop.
log:
```
INFO 2020-02-16 09:00:30,951 nabd started
DEBUG 2020-02-16 09:00:36,261 Using selector: EpollSelector
DEBUG 2020-02-16 09:01:31,342 Traceback (most recent call last):
  File "/home/pi/pynab/nabd/nabd.py", line 150, in idle_worker_loop
    await self._do_transition_to_idle()
  File "/home/pi/pynab/nabd/nabd.py", line 134, in _do_transition_to_idle
    await self.nabio.move_ears_with_leds((255, 0, 255), left, right)
  File "/home/pi/pynab/nabd/nabio.py", line 40, in move_ears_with_leds
    current_left, current_right = await self.ears.get_positions()
TypeError: object tuple can't be used in 'await' expression

DEBUG 2020-02-16 09:01:31,463 packet from service: {'type': 'mode', 'mode': 'idle', 'events': ['asr', 'rfid/nabtaichid']}
DEBUG 2020-02-16 09:01:31,466 packet from service: {'type': 'mode', 'mode': 'idle', 'events': ['asr']}
DEBUG 2020-02-16 09:01:31,483 packet from service: {'type': 'mode', 'mode': 'idle', 'events': ['button', 'asr'], 'request_id': 'idle-button'}
DEBUG 2020-02-16 09:01:31,486 packet from service: {'type': 'mode', 'mode': 'idle', 'events': ['asr', 'rfid/nabsurprised']}
DEBUG 2020-02-16 09:01:31,497 packet from service: {'type': 'mode', 'mode': 'idle', 'events': ['asr']}
DEBUG 2020-02-16 09:01:31,504 packet from service: {'type': 'message', 'signature': {'audio': ['nabclockd/signature.mp3']}, 'body': [{'audio': ['nabclockd/9/*.mp3']}], 'expiration': '2020-02-16T09:03:55.269274'}
DEBUG 2020-02-16 09:01:31,507 packet from service: {'type': 'mode', 'mode': 'idle', 'events': ['asr']}
DEBUG 2020-02-16 09:01:31,513 packet from service: {'type': 'info', 'info_id': 'nabairqualityd', 'animation': {'tempo': 42, 'colors': [{'left': '00ffff', 'center': '00ffff', 'right': '00ffff'}, {'left': '00ffff', 'center': '00ffff', 'right': '00ffff'}, {'left': '00ffff', 'center': '00ffff', 'right': '00ffff'}, {'left': '000000', 'center': '000000', 'right': '000000'}]}}
DEBUG 2020-02-16 09:01:31,520 packet from service: {'type': 'mode', 'mode': 'idle', 'events': ['asr', 'rfid/nabweatherd']}
DEBUG 2020-02-16 09:01:31,527 packet from service: {'type': 'info', 'info_id': 'nabweatherd', 'animation': {'tempo': 125, 'colors': [{'left': '000000', 'center': 'ffff00', 'right': '000000'}, {'left': '0000ff', 'center': '000000', 'right': '0000ff'}]}}
```

**Comment by pguyot** [comment]
Oops. There was an inconsistency in the API interface, 419ac7f should fix this.

**Comment by cyril1929** [comment]
It's not correct yet :
```
INFO 2020-02-16 09:13:26,195 nabd started
DEBUG 2020-02-16 09:13:30,601 Using selector: EpollSelector
INFO 2020-02-16 09:19:33,040 nabd started
DEBUG 2020-02-16 09:19:37,071 Using selector: EpollSelector
DEBUG 2020-02-16 09:21:01,884 Traceback (most recent call last):
  File "/home/pi/pynab/nabd/nabd.py", line 150, in idle_worker_loop
    await self._do_transition_to_idle()
  File "/home/pi/pynab/nabd/nabd.py", line 134, in _do_transition_to_idle
    await self.nabio.move_ears_with_leds((255, 0, 255), left, right)
  File "/home/pi/pynab/nabd/nabio.py", line 42, in move_ears_with_leds
    if not self.ears.is_broken(Ears.LEFT_EAR):
NameError: name 'Ears' is not defined
```

**Comment by cyril1929** [comment]
It works.
Thank you for your reactivity!
