### ISSUE TITLE
sometimes nabd crashes

### ISSUE THREAD

**Issue by cyril1929** [nabaztag2018/pynab#133]
log :
```
DEBUG 2020-03-29 10:13:57,645 packet from service: {'type': 'message', 'signature': {'audio': ['nabsurprised/respirations/*.mp3']}, 'body': [{'audio': ['nabsurprised/03-29/*.mp3;nabsurprised/*.mp3']}], 'expiration': '2020-03-29T08:14:57.590567+00:00'}
DEBUG 2020-03-29 10:14:03,673 Traceback (most recent call last):
  File "/home/pi/pynab/nabd/nabd.py", line 156, in idle_worker_loop
    await self.process_idle_item(item)
  File "/home/pi/pynab/nabd/nabd.py", line 223, in process_idle_item
    await self.perform(item[0], item[1])
  File "/home/pi/pynab/nabd/nabd.py", line 764, in perform
    await self.nabio.play_message(signature, packet["body"])
  File "/home/pi/pynab/nabd/nabio.py", line 183, in play_message
    ci, preloaded_sig, ChoreographyInterpreter.STREAMING_URN
  File "/home/pi/pynab/nabd/nabio.py", line 217, in _play_preloaded
    seq_item["audio"], True, self.cancel_event
  File "/home/pi/pynab/nabd/sound.py", line 25, in play_list
    await self.stop_playing()
  File "/home/pi/pynab/nabd/sound_alsa.py", line 183, in stop_playing
    await self.wait_until_done()
  File "/home/pi/pynab/nabd/sound_alsa.py", line 186, in wait_until_done
    await wait_with_cancel_event(self.future, event, self.stop_playing)
  File "/home/pi/pynab/nabd/cancel.py", line 20, in wait_with_cancel_event
    await task
  File "/home/pi/pynab/nabd/choreography.py", line 433, in play
    await self.play_binary(chor)
  File "/home/pi/pynab/nabd/choreography.py", line 312, in play_binary
    await self.do_play_binary(4, chor, opcodes, timescale)
  File "/home/pi/pynab/nabd/choreography.py", line 345, in do_play_binary
    index = await handler(index, chor)
  File "/home/pi/pynab/nabd/choreography.py", line 300, in attend
    await self.sound.wait_until_done(self.cancel_event)
  File "/home/pi/pynab/nabd/sound_alsa.py", line 186, in wait_until_done
    await wait_with_cancel_event(self.future, event, self.stop_playing)
  File "/home/pi/pynab/nabd/cancel.py", line 20, in wait_with_cancel_event
    await task
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/pynab/nabd/sound_alsa.py", line 287, in <lambda>
    self.executor, lambda f=filename: self._play(f)
  File "/home/pi/pynab/nabd/sound_alsa.py", line 137, in _play
    mp3 = Mpg123(filename)
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/mpg123.py", line 110, in __init__
    self._lib = self.init_library(library_path)
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/mpg123.py", line 99, in init_library
    raise self.LibInitializationException('libmpg123 not found')
mpg123.Mpg123.LibInitializationException: libmpg123 not found

DEBUG 2020-03-29 11:05:49,270 broadcast event: ears, {'type': 'ears_event', 'left': 10, 'right': 11}
```

**Comment by pguyot** [comment]
This issue was fixed with 0.8.0.
