### ISSUE TITLE
Exception "ConnectionResetError(104, 'Connection reset by peer')" should be caught in nabservice.py:48

### ISSUE THREAD

**Issue by nabaztag2018** [nabaztag2018/pynab#387]
On certain occasion, when restarting nabd, this exception can occur. 

==> /var/log/nabweatherd.log <==
2022-06-12 11:55:40,589 [ERROR] nabweatherd: Task exception was never retrieved
future: <Task finished coro=<NabService.client_loop() done, defined at /home/pi/pynab/nabcommon/nabservice.py:48> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/home/pi/pynab/nabcommon/nabservice.py", line 77, in client_loop
    line = await self.reader.readline()
  File "/usr/lib/python3.7/asyncio/streams.py", line 496, in readline
    line = await self.readuntil(sep)
  File "/usr/lib/python3.7/asyncio/streams.py", line 588, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

==> /var/log/nabtaichid.log <==
2022-06-12 11:55:40,638 [ERROR] nabtaichid: Task exception was never retrieved
future: <Task finished coro=<NabService.client_loop() done, defined at /home/pi/pynab/nabcommon/nabservice.py:48> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/home/pi/pynab/nabcommon/nabservice.py", line 77, in client_loop
    line = await self.reader.readline()
  File "/usr/lib/python3.7/asyncio/streams.py", line 496, in readline
    line = await self.readuntil(sep)
  File "/usr/lib/python3.7/asyncio/streams.py", line 588, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-06-12 11:56:03,763 [INFO] nabtaichid: started with log level INFO

**Comment by pguyot** [comment]
This makes sense. If nabd is restarted, services get disconnected.
