### ISSUE TITLE
Taichi crash / due to polyglotte modification

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#65]
==> /var/log/nabd.log <==
DEBUG 2020-01-03 15:23:02,248 type choreographies
DEBUG 2020-01-03 15:23:02,251 filename nabtaichid/taichi.chor
DEBUG 2020-01-03 15:23:02,294 type sounds
DEBUG 2020-01-03 15:23:02,296 filename choreographies/3notesB5D5C6.mp3
DEBUG 2020-01-03 15:23:02,322 first_parent choreographies
INFO 2020-01-03 15:23:02,329 Crash in choreography interpreter: Traceback (most recent call last):
  File "/home/pi/pynab/nabd/choreography.py", line 419, in play
    await self.play_binary(chor)
  File "/home/pi/pynab/nabd/choreography.py", line 300, in play_binary
    await self.do_play_binary(4, chor, opcodes, timescale)
  File "/home/pi/pynab/nabd/choreography.py", line 333, in do_play_binary
    index = await handler(index, chor)
  File "/home/pi/pynab/nabd/choreography.py", line 267, in randmidi
    random.choice(ChoreographyInterpreter.MIDI_LIST)
  File "/home/pi/pynab/nabd/sound.py", line 31, in start_playing
    preloaded = await self.preload(audio_resource)
  File "/home/pi/pynab/nabd/sound.py", line 10, in preload
    file = await Resources.find("sounds", audio_resource)
  File "/home/pi/pynab/nabd/resources.py", line 38, in find
    result = await Resources._find_file(type, filename)
  File "/home/pi/pynab/nabd/resources.py", line 61, in _find_file
    for item in os.listdir(path_locales_directory):
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pynab/choreographies/sounds'

**Comment by 232enero** [comment]
multilingual support will be done elsewhere
back to normal
