### ISSUE TITLE
mpg123.Mpg123.LibInitializationException: libmpg123 not found

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#66]
**Après un test de reconnaissance vocale :**

==> /var/log/nabd.log <==
ERROR 2020-01-04 17:45:16,894 Task exception was never retrieved
future: <Task finished coro=<Nabd.stop_asr() done, defined at /home/pi/pynab/nabd/nabd.py:607> exception=LibInitializationException('libmpg123 not found')>
Traceback (most recent call last):
  File "/home/pi/pynab/nabd/nabd.py", line 608, in stop_asr
    await self.nabio.end_acquisition()
  File "/home/pi/pynab/nabd/nabio.py", line 103, in end_acquisition
    await self.sound.stop_recording()
  File "/home/pi/pynab/nabd/sound_alsa.py", line 227, in stop_recording
    await self.wait_until_done()
  File "/home/pi/pynab/nabd/sound_alsa.py", line 186, in wait_until_done
    await self.future
  File "/home/pi/pynab/nabd/nabd.py", line 608, in stop_asr
    await self.nabio.end_acquisition()
  File "/home/pi/pynab/nabd/nabio.py", line 103, in end_acquisition
    await self.sound.stop_recording()
  File "/home/pi/pynab/nabd/sound_alsa.py", line 227, in stop_recording
    await self.wait_until_done()
  File "/home/pi/pynab/nabd/sound_alsa.py", line 186, in wait_until_done
    await self.future
  File "/home/pi/pynab/nabd/nabd.py", line 605, in start_asr
    await self.nabio.start_acquisition(self.asr.decode_chunk)
  File "/home/pi/pynab/nabd/nabio.py", line 96, in start_acquisition
    await self.sound.play_list(["asr/listen.mp3"], False)
  File "/home/pi/pynab/nabd/sound.py", line 28, in play_list
    await self.wait_until_done()
  File "/home/pi/pynab/nabd/sound_alsa.py", line 186, in wait_until_done
    await self.future
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/pynab/nabd/sound_alsa.py", line 287, in <lambda>
    self.executor, lambda f=filename: self._play(f)
  File "/home/pi/pynab/nabd/sound_alsa.py", line 136, in _play
    mp3 = Mpg123(filename)
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/mpg123.py", line 110, in __init__
    self._lib = self.init_library(library_path)
  File "/home/pi/pynab/venv/lib/python3.7/site-packages/mpg123.py", line 99, in init_library
    raise self.LibInitializationException('libmpg123 not found')
mpg123.Mpg123.LibInitializationException: libmpg123 not found

**Comment by pguyot** [comment]
libmpg123 is part of declared dependencies and installed on release images.
